---
  - name: Init Swarm Master
    hosts: tag_Name_master
    gather_facts: False
    remote_user: centos
    become: yes
    become_user: root
    tasks:
     # - name: Swarm Init
     #   command: docker swarm init --advertise-addr {{ inventory_hostname }}

      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Show Worker Token
        debug: var=worker_token.stdout

      - name: Master Token
        command: docker swarm join-token manager -q
        register: master_token

      - name: Show Master Token
        debug: var=master_token.stdout

  - name: Join Swarm Cluster
    hosts: tag_Name_worker_1
    gather_facts: False
    remote_user: centos
    become: yes
    become_user: root
    vars:
      token: "{{ hostvars[groups['tag_Name_master'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['tag_Name_master'][0]]['inventory_hostname'] }}"
    tasks:
      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ master }}:2377
        register: worker

      - name: Show Results
        debug: var=worker.stdout

      - name: Show Errors
        debug: var=worker.stderr

  - name: Join Swarm Cluster
    hosts: tag_Name_worker_2
    gather_facts: False
    remote_user: centos
    become: yes
    become_user: root
    vars:
      token: "{{ hostvars[groups['tag_Name_master'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['tag_Name_master'][0]]['inventory_hostname'] }}"
    tasks:
      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ master }}:2377
        register: worker

      - name: Show Results
        debug: var=worker.stdout

      - name: Show Errors
        debug: var=worker.stderr
